crawler_map = {
    "IndeedPostingCrawler": "ca.indeed.com",
    "TalgroupPostingCrawler": "talgroup.net",
    "WorkdayPostingCrawler": "myworkdaypostings.com",
    "AerotekPostingCrawler": "www.aplitrak.com",
    "SmoothHiringPostingCrawler": "app.smoothhiring.com",
    "RBCPostingCrawler": "postings.rbc.com",
    "BrassRingPostingCrawler": "krb-spostings.brassring.com",
    "EaglePostingCrawler": "postings.eagleonline.com",
    "TaleoPostingCrawler": "taleo.net",
    "DavidAplinPostingCrawler": "www.aplin.com",
    "ADPPostingCrawler": "workforcenow.adp.com",
    "JobDivaPostingCrawler": "postingdiva.com",
    "RecruitingInMotionPostingCrawler": "recruitinginmotion.com",
    "WebConnectPostingCrawler": "webconnect.sendouts.net",
    "AkamaiPostingCrawler": "https: //www.akamai.com",
    "IanMartinPostingCrawler": "careers.ianmartin.com",
    "TeksystemsPostingCrawler": "www.teksystems.com",
    "HireGooglePostingCrawler": "hire.withgoogle.com",
    "GooglePostingCrawler": "careers.google.com",
    "GenericPostingCrawler": ""
}
